name: redstone
version: 0.6.4
authors:
  - Luiz Mineo <luiz.mineo@gmail.com>
  - Kenneth Endfinger <kaendfinger@gmail.com>
  - Austin Cummings <austincummings95@gmail.com>
  - Cristian Garcia <cgarcia.e88@gmail.com>
  - Joel Trottier-Hebert <iamquebecois@gmail.com>
description: A metadata driven microframework for Dart
homepage: http://redstonedart.org
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  collection: "^1.2.0"
  crypto: "^0.9.1"
  di: "^3.3.6"
  grinder: "^0.8.0+1"
  mime: "^0.9.3"
  http: "^0.11.3+3"
  http_parser: '>=1.0.0 <3.0.0'
  http_server: "^0.9.5+1"
  route_hierarchical: "^0.6.2"
  shelf: "^0.6.4+3"
  stack_trace: "^1.5.0"
dev_dependencies:
  test: "^0.12.6+1"
